<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="ShoppingCart.aspx.cs" Inherits="Group8MasterPage.ShoppingCart" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <asp:GridView runat="server" ID="ShoppingCartGrid" AutoGenerateDeleteButton="True" OnRowDeleting="ShoppingCartGrid_RowDeleting"></asp:GridView>
    <div class="total">
        <asp:Label ID="lblTotal" runat="server" Text="Total"></asp:Label>
        <asp:Label ID="numberTotal" runat="server" Text=""></asp:Label>
        <br />
        <asp:Button ID="btnPurchase" runat="server" Text="Purchase" OnClientClick="javascript:Popup()" OnClick="btnPurchase_Click" />
    </div>
    <script language="javascript">

        function Popup()
        {
            window.prompt("Enter you email or log in", "defaultText");

        }

</script>
</asp:Content>
    